# Generated by Django 3.1.7 on 2021-03-31 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip', models.BooleanField(default=False)),
                ('damage', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('descript', models.TextField()),
                ('tier', models.IntegerField()),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Npc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npc_name', models.CharField(max_length=55)),
                ('npc_level', models.CharField(max_length=55)),
                ('npc_strength', models.IntegerField()),
                ('npc_hitpoints', models.IntegerField()),
                ('npc_agility', models.IntegerField()),
                ('npc_endurance', models.IntegerField()),
                ('npc_intelligence', models.IntegerField()),
                ('npc_defense', models.IntegerField()),
                ('npc_descrip', models.TextField()),
                ('npc_tameable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.CharField(max_length=255)),
                ('planet_type', models.CharField(max_length=255)),
                ('planet_desc', models.TextField()),
                ('planet_region', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('strength', models.IntegerField()),
                ('hitpoints', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('endurance', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('descrip', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_name', models.CharField(max_length=55)),
                ('ship_class', models.CharField(max_length=55)),
                ('ship_speed_modifier', models.IntegerField()),
                ('ship_desc', models.CharField(default='null', max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(max_length=25)),
                ('skill_level', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('time_to_complete', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill_Que',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_in_que', models.CharField(max_length=25)),
                ('skills', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='app_one.skill')),
            ],
        ),
    ]
