# Generated by Django 3.1.7 on 2021-03-31 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Char_First_Name', models.CharField(max_length=25)),
                ('Char_Last_Name', models.CharField(max_length=25)),
                ('Char_Level', models.IntegerField()),
                ('Char_Profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Character', to='app_one.profession')),
                ('Char_Race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='app_one.race')),
                ('Char_Skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Characters', to='app_one.skill')),
                ('Char_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='app_one.user')),
            ],
        ),
    ]
